### ISSUE TITLE
Undefined index notice

### ISSUE THREAD

**Issue by renventura** [maor/wp-widget-labels#2]
Hey, Maor. Love the plugin! I was actually thinking of writing something myself to achieve the same thing because I am using a number of widgets without titles, and it's a hassle to have open each one before editing them. Awesome work, and thanks for creating it.

One bug I've run into is that the plugin will cause an undefined index notice to display in the label input when WP_DEBUG is enabled, and no label has saved. The notice is as follows:

`Undefined index: mc_widget_label in {...}/wp-content/plugins/widget-labels/widget-labels.php on line 93`

This causes the widget's label to be that undefined index notice. Not a major deal, but I thought I'd bring it up. It's a quick fix (just check that the mc_widget_label key is set), and, if you'd like, I'm happy to submit a PR.

Thanks again.

**Comment by maor** [comment]
Thanks for your feedback, @EngageWP. I'm happy to hear this is useful to you!
Please let me know if this fixed the issue as I assume it did.
